### ISSUE TITLE
Nothing happen when i click on next

### ISSUE THREAD

**Issue by SarahClerge** [cybertec-postgresql/cybertec_migrator#27]
### 📝 Description

I installed the product on my machine, it manages to connect well to my oracle database, but when I press the next button on the selection screen of what I want to migrate, nothing happens .

### 📜 Steps to reproduce

1. Install migrator
2. Go on the app
3. Create a new migration
4. Fill in the fields of the login form
5. Click on check
6. Click on next
7. On the next page select the data you want to migrate by checking in the list
8. click on the next button

### 🙁 Actual behavior

I think it is supposed to do something... But nothing appen. No session on my oracle database, no loading message... Just nothing, even after i click on next several time.
The "Target Connection" step stay grey and the "schema selection" stay blue with the 2 in the circle

### 🙂 Expected behavior

Show me the target connection page, or at least give me access to it

### Migrator version

3.16.0

### In which environment are you operating?

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other

### What browser are you using

Chrome

### Other

![chrome_Jl4fKVz8Cv](https://user-images.githubusercontent.com/113909496/236260019-b88e5cad-a137-4e19-b80e-faa14b6194b8.png)

**Comment by KieranKaelin** [comment]
Hello Sarah,

This is a know bug in `v3.16.0`, an has been fixed in the subsequent patches. Please use the newest version as highlighted here https://github.com/cybertec-postgresql/cybertec_migrator/issues/25#issuecomment-1533364340.
