### ISSUE TITLE
cybertec migrator fails during the Analyze step

### ISSUE THREAD

**Issue by GeorgesBAZ** [cybertec-postgresql/cybertec_migrator#28]
### 📝 Description

An unexpected error occurred. If this error happens repeatedly,

### 📜 Steps to reproduce

cybertec migrator fails during the Analyze step

### 🙁 Actual behavior

cybertec migrator fails during the Analyze step

### 🙂 Expected behavior

cybertec migrator fails during the Analyze step

### Migrator version

3.16.4

### In which environment are you operating?

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other

### What browser are you using

FireFox

**Comment by KieranKaelin** [comment]
Hello Georges!

Most likely this is due to some specific Oracle system catalog incarnation that our Migrator does not cover yet.
Would you be so kind as to provide us the logs? You may retrieve them by opening the Help menu (the `?` at the top right) and selecting `Dowload Logs`).

Cheers,
Kieran

**Comment by Schmaetz** [comment]
@GeorgesBAZ  @KieranKaelin 
Closed due to lack of feedback from the issue creator.
