### ISSUE TITLE
500 error 

### ISSUE THREAD

**Issue by maiksandmann** [cybertec-postgresql/cybertec_migrator#31]
### 📝 Description

connection to postgresql azure is not working

### 📜 Steps to reproduce

1. steps followed from the githp
2. deployment
3. connection 

### 🙁 Actual behavior

error 500 

### 🙂 Expected behavior

connection successfu

### Migrator version

3.18.4

### In which environment are you operating?

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other

### What browser are you using

edge

### Other

need support

**Comment by Schmaetz** [comment]
bug cannot be reproduced. 
connection via flexible server possible, as long as the destination is reachable.
