### ISSUE TITLE
'insufficient privileges SELECT_CATALOG_ROLE' error despite role being set

### ISSUE THREAD

**Issue by moritz-hr** [cybertec-postgresql/cybertec_migrator#33]
### 📝 Description

In the source connection step, when checking the database connection the following error is shown:
```
insufficient privileges to perform migration
Hint: execute the following query: GRANT SELECT_CATALOG_ROLE TO mtrost_hr_ref
```
The GRANT query has been run and SELECT_CATALOG_ROLE is present in user_role_privs for this user.

I suspect there is some other issue, but the logs I could find did not contain any information.
Is there a way for me to investigate the problem further?

### 📜 Steps to reproduce

Check source database connection

### 🙁 Actual behavior

Possibly misleading/ wrong error message/ hint

### 🙂 Expected behavior

Correct Hint to resolve the issue

### Migrator version

3.18.4

### In which environment are you operating?

- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Other

### What browser are you using

Edge

**Comment by KieranKaelin** [comment]
Hello @moritz-hr.

What Oracle version are you attempting to connect to? We might not have it covered in our CI setup.

Using the provided Oracle credentials, we execute the following three queries, and check if there is a row for each. 
```sql
SELECT role FROM SESSION_ROLES WHERE role = 'SELECT_CATALOG_ROLE';
SELECT privilege FROM SESSION_PRIVS WHERE privilege = 'SELECT ANY TABLE';
SELECT privilege FROM SESSION_PRIVS WHERE privilege = 'FLASHBACK ANY TABLE';
```

Could you test if the first query returns a result on your database?

**Comment by moritz-hr** [comment]
Hi, its Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0 - Production
Version 19.16.0.0.0

Thanks for the reply, it helped already.
I was able to fix it, the issue was that the role was granted but not marked as default.
I guess the migrator could also try to 'SET ROLE SELECT_CATALOG_ROLE' in its session.

**Comment by KieranKaelin** [comment]
That is a good tip, thank you. We'll incorporate it into our backlog to have this issue resolved automatically in the future.
I will close the ticket, thank you for reaching out to us!
